#!/usr/bin/env sh

JENKINS_TAG=`date -u +"%Y-%m-%dT%H:%M:%SZ"`

echo "------ HOOK START - BUILD -------"
printenv

docker build -t ${DOCKER_REPO}:${JENKINS_TAG} ./

echo "------ HOOK END - BUILD -------"
